/*
 * generated by Xtext 2.29.0
 */
package kotlinprogram.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyKTUiModule extends AbstractMyKTUiModule {

	public MyKTUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
