/*
 * generated by Xtext 2.29.0
 */
package kotlinprogram;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyKTStandaloneSetup extends MyKTStandaloneSetupGenerated {

	public static void doSetup() {
		new MyKTStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
