/*
 * generated by Xtext 2.30.0
 */
package kotlinMetaModel.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kotlinMetaModel.MyDslRuntimeModule;
import kotlinMetaModel.MyDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyDslIdeSetup extends MyDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyDslRuntimeModule(), new MyDslIdeModule()));
	}
	
}
