/*
 * generated by Xtext 2.30.0
 */
package kotlinMetaModel;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends AbstractMyDslRuntimeModule {
}
