/*
 * generated by Xtext 2.29.0
 */
package kotlin.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import kotlin.language.MyKTRuntimeModule;
import kotlin.language.MyKTStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MyKTIdeSetup extends MyKTStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MyKTRuntimeModule(), new MyKTIdeModule()));
	}
	
}
