<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kotlinMetaModel" nsURI="http://www.example.org/kotlinMetaModel"
    nsPrefix="kotlinMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="KotlinProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignement" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignement" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassConstruction" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoOperation" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLineComment" eSuperTypes="#//Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" eType="#//Line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiLineComment" eSuperTypes="#//Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" upperBound="-1"
        eType="#//Line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true" eSuperTypes="#//NoOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" lowerBound="1" eType="#//body"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="body">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" upperBound="-1"
        eType="#//Line" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line"/>
</ecore:EPackage>
