<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="kotlinMetaModel" nsURI="http://www.example.org/kotlinMetaModel"
    nsPrefix="kotlinMetaModel">
  <eClassifiers xsi:type="ecore:EClass" name="KotlinProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="import" upperBound="-1"
        eType="#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Declaration" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignement" abstract="true" eSuperTypes="#//Instruction #//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassDeclaration" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionDeclaration" eSuperTypes="#//Declaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="return" lowerBound="1"
        eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableDeclaration" eSuperTypes="#//Declaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableAssignement" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassConstruction" eSuperTypes="#//Assignement"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoOperation" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment" abstract="true" eSuperTypes="#//NoOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//Package"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kotlinProgram" upperBound="-1"
        eType="#//KotlinProgram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLineComment" eSuperTypes="#//Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" eType="#//Line"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleLineComment" eSuperTypes="#//Comment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" lowerBound="1" upperBound="-1"
        eType="#//Line" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimitiveType" abstract="true" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Int" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignement" lowerBound="1"
        eType="#//Assignement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//PrimitiveType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//PrimitiveType"/>
</ecore:EPackage>
